### ISSUE TITLE
MongoDB filter by ID field not working?

### ISSUE THREAD

**Issue by Atlinx** [twinlogix/typetta#207]
I have this piece of code
```typescript
// BROKEN
const userRoles = await entityManager.userRole.findAll({
    filter: {
      userId: { eq: checkUserId }
    }
  });
```

and this schema
```graphql
type UserRole @entity @mongodb {
  id: ID! @id(from: "db") @alias(value: "_id")
  role: Role! @innerRef(refFrom: "roleCode", refTo: "code")
  roleCode: RoleCode!
  user: User! @innerRef
  userId: ID!
}
```

When I run the code, `userRoles` is blank. `checkUserId` exists in the database, and there also exists a `UserRole` whose `userId == checkUserId`. I'm using MongoDB, and `checkUserId` is a `string`.

Note that running `findAll` without any arguments correctly fetchs all the `UserRole`s, including the one I wanted to fetch using the `filter` option:
```typescript
// WORKS
const userRoles = await entityManager.userRole.findAll();
```

I think this might be a bug.

**Comment by Atlinx** [comment]
Upon further testing, it looks like `checkUserId` isn't working for any of the find statements
```typescript
  // checkUserId == "628c7fb3abfea029c993ef47"
  // userRoles == []
  const userRoles = await entityManager.userRole.findAll({
    filter: {
      userId: checkUserId
    }
  });
  // testA == null
  const testA = await entityManager.userRole.findOne({
    filter: {
      userId: checkUserId
    }
  });
  // testB == null
  const testB = await entityManager.user.findOne({
    filter: {
      id: checkUserId
    }
  });
  // testC == []
  const testC = await entityManager.user.findAll({
    filter: {
      id: checkUserId
    }
  });
```

**Comment by minox86** [comment]
Are you sure the variable you are passing is a corrent id as string? We are
pretty sure that the filter works correctly as you experienced in your last
test.

I suggest you to double check the value at runtime, maybe it is an ObjectId
and not a String?!

Il Mar 24 Mag 2022, 22:05 Atlinx ***@***.***> ha scritto:

**Comment by Atlinx** [comment]
Yeah I was debugging it and it's a string. Even if it were an ObjectId it shouldn't matter because Typetta forces userId to be a string.

**Comment by Atlinx** [comment]
I think there's a problem with how Typetta currently builds MongoDB filters.

![image](https://user-images.githubusercontent.com/25368491/170154394-1f47e9a1-3b43-45be-9244-e11dc3c37a2d.png)

In the debugging window above, the built filter is 
```typescript
filter: {
  userId: { $eq: '628c7fb3abfea029c993ef47' }
}
```

This filter doesn't work because it's using the id as a string instead of an ObjectId
![image](https://user-images.githubusercontent.com/25368491/170154529-edc32cd3-6f50-4730-80a7-1564f35bc35e.png)
![image](https://user-images.githubusercontent.com/25368491/170154557-40e7a273-6012-4b1e-903a-7e1e1909d9e5.png)

**Comment by Atlinx** [comment]
Ok I've found the cause -- Typetta's typing for id's isn't actually true. The reason why 

```typescript
if (userLoginIdentity) {
    const user = await entityManager.user.findOne({ 
      filter: {
        id: { eq: userLoginIdentity.userId }
      }
    });
    return user;
  }
}
```

works is because `userLoginIdentity` was fetched from a previous find request. Inspecting `userLoginIdentity.userId` during debugging revealed it was actually an `ObjectId` type instead of a `string` type.

![image](https://user-images.githubusercontent.com/25368491/170155509-a3b15d56-3b95-4ff3-902f-b717148c39fc.png)

I've tried doing `<any>new ObjectId(userId)` to force a cast, but that just leads to
```
"TypeError: Context creation failed: Cannot read properties of undefined (reading 'ObjectId')"
```

**Comment by edobrb** [comment]
I think the problem here is that you are using ID scalar while defining it from "db", so the real value created is an ObjectId and not a string, but Typetta is expecting a string.
```
 id: ID! @id(from: "db") @alias(value: "_id")
 ```
That totally fine but you need to define a [DataTypeAdapter](https://twinlogix.github.io/typetta/chapters/data-model/scalars#scalar-adapter).
Try to define something like:
```
new EntityManager( { 
  scalars: {
        ID: {
          modelToDB: (value: string) => new ObjectId(value),
          dbToModel: (value: unknown) => {
            if (value && typeof value === 'object') {
              return value.toString()
            } else {
              throw new Error('Unexpected value for ID.')
            }
          },
    }
})
```
I also recommend to define a new scalar for ObjectId and map it to a string or an ObjectId as you prefer.

Let me know if that works.
