### ISSUE TITLE
Intellisense is missing for findOne and findAll projection

### ISSUE THREAD

**Issue by Atlinx** [twinlogix/typetta#248]

**Comment by edobrb** [comment]
By typing do you mean intellisense hints? If yes, we are aware of this problem. For now you can do something like this:
```
userDao.findAll({ projection: UserDAO.projection({ ...your projection... }})

//or

const projection: UserProjection = { ...your projection... }
userDao.findAll({ projection })
```

**Comment by Atlinx** [comment]
Yea I mean intellisense

**Comment by edobrb** [comment]
The problem is related to this: https://github.com/microsoft/TypeScript/issues/49456

**Comment by edobrb** [comment]
Version [2.0.0-10](https://www.npmjs.com/package/@twinlogix/typetta/v/2.0.0-10) should fix this

**Comment by Atlinx** [comment]
Projection Intellisense works now, but I'm also seeing `GraphQLResolveInfo` fields like `cacheControl` and `fieldName`. Is this intended?

**Comment by edobrb** [comment]
Yes, since the projetion field also accepts an `GraphQLResolveInfo` it also suggests those fields and I don't know how to avoid it.
