### ISSUE TITLE
Add an option for clearer `ModelProjection` return

### ISSUE THREAD

**Issue by edobrb** [twinlogix/typetta#70]
Now `ModelProjection` utility type return alway an object with the concatenation of the projection (`& { __projection: P }`). This is useful for a better type checking but it obfuscates the return type of find operations.

Proposal:
add `disableProjectionReturn` settings in the codegen.yml (default as false) that disable this behaviour.

`disableProjectionReturn: false`
![image](https://user-images.githubusercontent.com/50401517/149980879-70897aaa-1818-4510-a2a0-060fd42a95f5.png)

`disableProjectionReturn: true`
![image](https://user-images.githubusercontent.com/50401517/149981228-24b3a33b-68eb-4d3f-a151-f47b2f233d4a.png)

**Comment by minox86** [comment]
Can you please better explain type checking differences? What do you lose
with disableProjectionReturn true?

Il Mar 18 Gen 2022, 17:49 Edoardo Barbieri ***@***.***> ha
scritto:

**Comment by edobrb** [comment]
This simple example should clarify

```typescript
function something(user: ParamProjection<User, UserProjection, { firstName: true, posts: { title: true } }> | null) {
  // some computation on user.firstName and user.posts[x].title
}

// user1.posts is always undefined because relations are not loaded without excplicit projection 
const user1 = await dao.user.findOne()
something(user1) // disableProjectionReturn: true -> no compialtion error, false -> compilation error

// user2.posts are defined since projection is excplicit
const user2 = await dao.user.findOne({ projection: { firstName: true, posts: { title: true } } })
something(user2)
```
